    import{CONFIG,STATES}from'./config.js';import{Player}from'./player.js';import{Obstacle}from'./obstacle.js';import{intersects}from'./collision.js';import{Score}from'./score.js';
const mix=(a,b,t)=>{const n=s=>parseInt(s.slice(1),16),A=n(a),B=n(b),v=i=>Math.round(((A>>i)&255)*(1-t)+((B>>i)&255)*t);return`rgb(${v(16)},${v(8)},${v(0)})`};
export class Game{
constructor(canvas,restartButton,audio){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.restartButton=restartButton;this.audio=audio;this.state=STATES.MENU;this.score=new Score(()=>this.audio.record());this.last=0;this.resize();this.player=new Player(this.groundY);this.resetWorld();window.addEventListener('resize',()=>this.resize());document.addEventListener('visibilitychange',()=>{if(document.hidden&&this.state===STATES.PLAYING)this.pause()})}
resize(){const mobile=innerWidth<520;this.width=CONFIG.world.width;this.height=mobile?CONFIG.world.mobileHeight:CONFIG.world.desktopHeight;const dpr=Math.min(devicePixelRatio||1,2);this.canvas.width=this.width*dpr;this.canvas.height=this.height*dpr;this.ctx.setTransform(dpr,0,0,dpr,0,0);this.canvas.style.aspectRatio=`${this.width}/${this.height}`;this.groundY=Math.round(this.height*CONFIG.world.groundRatio);if(this.player){this.player.groundY=this.groundY;if(this.player.grounded)this.player.y=this.groundY-this.player.height}}
resetWorld(){this.obstacles=[];this.speed=CONFIG.game.initialSpeed;this.distance=0;this.groundOffset=0;this.spawnDistance=CONFIG.obstacle.initialGap}
jump(){if(this.state===STATES.MENU||this.state===STATES.GAME_OVER)return this.start();if(this.state!==STATES.PLAYING)return;if(this.player.jump())this.audio.jump()}duck(active){if(this.state===STATES.PLAYING)this.player.setDucking(active)}pause(){if(this.state===STATES.PLAYING){this.state=STATES.PAUSED;this.player.setDucking(false)}else if(this.state===STATES.PAUSED){this.state=STATES.PLAYING;this.last=performance.now()}}start(){this.state=STATES.PLAYING;this.restartButton.hidden=true;this.score.reset();this.resetWorld();this.player.reset(this.groundY)}over(){this.state=STATES.GAME_OVER;this.player.setDucking(false);this.score.commit();this.audio.collision();this.restartButton.hidden=false}
nextGap(){const o=CONFIG.obstacle,reduction=Math.min(110,this.score.value*o.gapReduction),speedSafety=(this.speed-CONFIG.game.initialSpeed)*.18;return Math.max(o.minGap,o.maxGap-reduction+speedSafety*Math.random())}
nightAmount(){const c=CONFIG.cycle,total=c.dayLength+c.transitionLength+c.nightLength+c.transitionLength,p=this.score.value%total;if(p<c.dayLength)return 0;if(p<c.dayLength+c.transitionLength)return(p-c.dayLength)/c.transitionLength;if(p<c.dayLength+c.transitionLength+c.nightLength)return 1;return 1-(p-c.dayLength-c.transitionLength-c.nightLength)/c.transitionLength}
palette(){const t=this.nightAmount(),c=CONFIG.colors;return{paper:mix(c.paper,c.nightPaper,t),ink:mix(c.ink,c.nightInk,t),night:t}}
update(dt){if(this.state!==STATES.PLAYING)return;this.speed=Math.min(CONFIG.game.maxSpeed,this.speed+CONFIG.game.acceleration*dt);this.distance+=this.speed*dt*CONFIG.game.scoreRate;this.score.update(this.distance,dt);this.groundOffset=(this.groundOffset+this.speed*dt)%42;this.spawnDistance-=this.speed*dt;if(this.spawnDistance<=0){this.obstacles.push(Obstacle.random(this.width+CONFIG.obstacle.spawnPadding,this.groundY,this.score.value));this.spawnDistance=this.nextGap()}this.player.update(dt);for(const o of this.obstacles){o.update(dt,this.speed);if(intersects(this.player,o)){this.over();break}}this.obstacles=this.obstacles.filter(o=>!o.offscreen)}
drawSky(p){if(p.night<=.02)return;const{ctx,width,height}=this;ctx.fillStyle=p.ink;ctx.globalAlpha=p.night*.75;for(let i=0;i<CONFIG.cycle.stars;i++){const x=(i*137+53)%width,y=48+(i*71)%(height*.48);ctx.fillRect(x,y,i%3===0?3:2,i%3===0?3:2)}ctx.globalAlpha=p.night;ctx.beginPath();ctx.arc(width*.12,height*.2,25,0,Math.PI*2);ctx.fill();ctx.fillStyle=p.paper;ctx.beginPath();ctx.arc(width*.135,height*.185,22,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}
draw(){const{ctx,width}=this,p=this.palette();ctx.clearRect(0,0,this.width,this.height);ctx.fillStyle=p.paper;ctx.fillRect(0,0,this.width,this.height);this.drawSky(p);ctx.strokeStyle=p.ink;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,this.groundY+.5);ctx.lineTo(width,this.groundY+.5);ctx.stroke();ctx.fillStyle=p.ink;for(let x=-this.groundOffset;x<width;x+=42){ctx.fillRect(x,this.groundY+10,3,2);ctx.fillRect(x+18,this.groundY+17,7,2)}for(const o of this.obstacles)o.draw(ctx,p);this.player.draw(ctx,p);this.score.draw(ctx,width,p);if(this.state===STATES.MENU)this.overlay('DINOGAME','ARRIBA: SALTAR  ·  ABAJO: AGACHARSE',p);if(this.state===STATES.PAUSED)this.overlay('PAUSA','P O ESC PARA CONTINUAR',p);if(this.state===STATES.GAME_OVER)this.overlay('GAME OVER',`PUNTOS ${this.score.value}`,p)}
overlay(title,subtitle,p){const{ctx,width,height}=this;ctx.textAlign='center';ctx.fillStyle=p.ink;ctx.font=`bold ${width<600?24:30}px Arial`;ctx.fillText(title,width/2,height*.36);ctx.font='12px Arial';ctx.fillText(subtitle,width/2,height*.43)}loop=t=>{const dt=Math.min((t-this.last)/1000||0,.034);this.last=t;this.update(dt);this.draw();requestAnimationFrame(this.loop)}
}
